apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: froystein-jp

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: froystein-jp
      app.kubernetes.io/managed-by: kargo
    includeSelectors: false

images:
  - name: ghcr.io/stianfro/froystein.jp
    newTag: latest
